server:
  port: 8080

spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver 
        url: jdbc:mysql://localhost:3306/userdb
        username: root
        password: E5E4LSKs
  data:
    jpa:
      repositories:
              enabled: true
        